---
- name: Add a new deploy key to GitHub repository {{ _cloud_init_ansible_pull_url }}
  community.general.github_deploy_key:
    owner: "{{ cloud_init_ansible_pull_repo_owner }}"
    repository: "{{ cloud_init_ansible_pull_repo_name }}"
    name: "{{ cloud_init_ansible_pull_deploy_key_name }}"
    key: "{{ _github_public_sshkey }}"
    force: true
    read_only: true
    token: "{{ cloud_init_github_token }}"
