---
- name: Assert required variables for role are defined
  ansible.builtin.include_tasks:
    file: assert.yaml
    apply:
      delegate_to: localhost
      run_once: true
      tags:
        - cloud_init_assert
  tags:
    - cloud_init_assert

- name: Create vm-cloud-init directory if not present
  ansible.builtin.file:
    path: "{{ cloud_init_path }}"
    state: directory
    mode: u=rwx,g=rx,o=x
    owner: root
    group: root
  become: true
  tags:
    - cloud_init_setup

- name: Generate templates for network data and user data
  block:
    - name: Template Network data
      ansible.builtin.include_tasks:
        file: network_data/main.yaml
      tags:
        - cloud_init_update
      when: cloud_init_template_networkdata is sameas true

    - name: Template User data
      ansible.builtin.include_tasks:
        file: user_data/main.yaml
      tags:
        - cloud_init_update
      when: cloud_init_template_userdata is sameas true
