---
- name: Fetch Github hostkeys
  ansible.builtin.include_tasks:
    file: prerequisites/github_hostkeys.yaml
    apply:
      tags:
        - cloud_init_update
  tags:
    - cloud_init_update

- name: Generate SSH keys for registering as deploy key
  ansible.builtin.include_tasks:
    file: prerequisites/ansible_pull/generate_ssh_key.yaml
    apply:
      tags:
        - cloud_init_update
  tags:
    - cloud_init_update
  when: cloud_init_enable_ansible_pull

- name: Generate signed host key
  ansible.builtin.include_tasks:
    file: prerequisites/generate_signed_host_key.yaml
    apply:
      tags:
        - cloud_init_update
  when: cloud_init_enable_ssh_ca

- name: Configure SSH CA
  ansible.builtin.include_tasks:
    file: prerequisites/ssh_ca.yaml
    apply:
      tags:
        - cloud_init_update
  tags:
    - cloud_init_update
  when: cloud_init_enable_ssh_ca

- name: Build ansible_pull github url
  ansible.builtin.set_fact:
    _cloud_init_ansible_pull_url: "git@github.com:{{ cloud_init_ansible_pull_repo_owner }}/{{ cloud_init_ansible_pull_repo_name }}.git"

- name: Fetch ansible_pull requirements.yaml file to embed in cloudinit
  ansible.builtin.include_tasks:
    file: prerequisites/ansible_pull/fetch_requirements.yaml
    apply:
      tags:
        - cloud_init_update
  tags:
    - cloud_init_update
  when: cloud_init_enable_ansible_pull

- name: Set correct SSH host ca variables
  block:
    - name: Fetch ssh_host_ca_ssh_keys when not defined
      ansible.builtin.include_vars:
        file: ssh_host_ca_keys.yaml
      when: not cloud_init_userdata.ssh_host_ca_keys is defined

    - name: Fetch ssh_host_ca_ssh_keys when not defined
      ansible.builtin.set_fact:
        _ssh_host_ca_keys: "{{ cloud_init_userdata.ssh_host_ca_keys }}"
      when: cloud_init_userdata.ssh_host_ca_ssh_keys is defined

- name: Set correct SSH ca write files variables
  block:
    - name: Fetch ssh_ca_write_files when not defined
      ansible.builtin.include_vars:
        file: ssh_ca_write_files.yaml
      when: not cloud_init_userdata.ssh_ca_write_files is defined

    - name: Fetch ssh_ca_write_files when not defined
      ansible.builtin.set_fact:
        _ssh_ca_write_files: "{{ cloud_init_userdata.ssh_ca_write_files }}"
      when: cloud_init_userdata.ssh_ca_write_files is defined

- name: Create cloud_init user-data template
  ansible.builtin.template:
    src: user-data/config.yaml.j2
    dest: "{{ cloud_init_path }}/user-data-{{ cloud_init_machine_name }}.yaml"
    validate: cloud-init schema --config-file %s
    mode: u=rw,g=r,o=
  become: true
  tags:
    - cloud_init_update

- name: Register Github Deploy SSH key
  ansible.builtin.include_tasks:
    file: postactions/ansible_pull/register_github_deploy_key.yaml
    apply:
      tags:
        - cloud_init_update
  tags:
    - cloud_init_update
  when: cloud_init_enable_ansible_pull

- name: Add Host CA to known hosts
  ansible.builtin.include_tasks:
    file: postactions/add_ca_to_known_hosts.yaml
    apply:
      tags:
        - cloud_init_update
  tags:
    - cloud_init_update
  when: cloud_init_add_to_known_hosts and cloud_init_enable_ssh_ca
