---
- name: Generate client config
  delegate_to: "localhost"
  block:
    - name: Create and change permission on temporary key directory (controller)
      ansible.builtin.tempfile:
        state: directory
      check_mode: false
      changed_when: false
      register: tempfile

    - name: Get repo name
      ansible.builtin.set_fact:
        _cloud_init_ansible_pull_repo_name: '{{ cloud_init_ansible_pull_url | regex_replace("/(.*)\.", "\1") }}'

    - name: Fetch ansible pull requirements file from pull repo
      ansible.builtin.git:
        repo: "{{ cloud_init_ansible_pull_url }}"
        dest: "{{ tempfile.path }}/{{ _cloud_init_ansible_pull_repo_name }}"
        update: true
        version: main

    - name: Fetch ansible pull requirements file from pull repo
      ansible.builtin.set_fact:
        _cloud_init_ansible_pull_requirements_yaml: >-
          "{{ lookup('ansible.builtin.file', tempfile.path + '/' + _cloud_init_ansible_pull_repo_name + '/' + 'requirements.yaml') }}"
      ignore_errors: "{{ ansible_check_mode }}"

    - name: Set generated key as fact
      ansible.builtin.set_fact:
        # default filter for allowing checkmode to generate a template
        _cloud_init_ansible_pull_requirements_yaml: "{{  cloud_init_ansible_pull_requirements_yaml | default('---\n<< will be populated >>') }}"

  always:
    - name: Remove temporary directory (controller)
      ansible.builtin.file:
        name: "{{ tempfile.path }}"
        state: absent
      check_mode: false
      changed_when: false
      delegate_to: "localhost"
